language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  exclude:
  allow_failures:
    - python: "2.7"
      env: DJANGO="2.0b1"
    - python: "3.4"
      env: DJANGO="2.0b1"
    - python: "3.5"
      env: DJANGO="2.0b1"
    - python: "3.6"
      env: DJANGO="2.0b1"
    - python: "2.7"
      env: DJANGO="dev"
    - python: "3.4"
      env: DJANGO="dev"
    - python: "3.5"
      env: DJANGO="dev"
    - python: "3.6"
      env: DJANGO="dev"

install:
   - "if [[ $DJANGO == 'dev' ]]; then pip install git+https://github.com/django/django.git#egg=Django; else pip install Django~=$DJANGO; fi"
   - pip install -r requirements.txt
   - python setup.py develop
env:
  - DJANGO="1.8.0"
  - DJANGO="1.9.0"
  - DJANGO="1.10.0"
  - DJANGO="1.11.0"
  - DJANGO="2.0"
  - DJANGO="2.1"
  - DJANGO="dev"
script: python setup.py test
