language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="1.7.0"
    - python: "2.6"
      env: DJANGO="1.8.0"
    - python: "2.6"
      env: DJANGO="1.9.0"
    - python: "2.6"
      env: DJANGO="1.10.0"
    - python: "2.6"
      env: DJANGO="dev"
    - python: "3.3"
      env: DJANGO="1.4.0"
    - python: "3.3"
      env: DJANGO="1.9.0"
    - python: "3.3"
      env: DJANGO="1.10.0"
    - python: "3.3"
      env: DJANGO="dev"
    - python: "3.4"
      env: DJANGO="1.4.0"
    - python: "3.5"
      env: DJANGO="1.4.0"
    - python: "3.5"
      env: DJANGO="1.5.0"
    - python: "3.5"
      env: DJANGO="1.6.0"
    - python: "3.5"
      env: DJANGO="1.7.0"
  allow_failures:
    - python: "2.7"
      env: DJANGO="1.10.0"
    - python: "2.7"
      env: DJANGO="dev"
    - python: "3.4"
      env: DJANGO="1.10.0"
    - python: "3.5"
      env: DJANGO="1.10.0"
    - python: "3.4"
      env: DJANGO="dev"
    - python: "3.5"
      env: DJANGO="dev"

install:
   - "if [[ $DJANGO == 'dev' ]]; then pip install git+https://github.com/django/django.git#egg=Django; else pip install Django~=$DJANGO; fi"
   - pip install -r requirements.txt
   - python setup.py develop
env:
  - DJANGO="1.4.0"
  - DJANGO="1.5.0"
  - DJANGO="1.6.0"
  - DJANGO="1.7.0"
  - DJANGO="1.8.0"
  - DJANGO="1.9.0"
  - DJANGO="1.10.0"
  - DJANGO="dev"
script: python setup.py test
