language: python
python:
  - "2.6"
  - "2.7"
install:
   - "if [[ $DJANGO == 'dev' ]]; then pip install git+https://github.com/django/django.git@stable/1.5.x#egg=Django; else pip install Django==$DJANGO --use-mirrors; fi"
   - pip install -r requirements.txt --use-mirrors
   - python setup.py develop
env:
  - DJANGO="1.3.7"
  - DJANGO="1.4.5"
  - DJANGO="1.5.1"
  - DJANGO="dev"
script: python setup.py test
